language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  # PyPy versions
  - "pypy"
  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0
# - "pypy-5.3.1"
# command to install dependencies

virtualenv:
  system_site_packages: true

install:
  #- pip install -r requirements.txt
  - cat requirements.txt | xargs pip install
  - pip install .

# command to run tests
script: nosetests