language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  # PyPy versions
#  - "pypy"
# - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0
# - "pypy-5.3.1"
# command to install dependencies

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install python-tk

install:
  - sudo pip install --install-option='--no-cython-compile' cython
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
  - python setup.py build_ext -i
  #- pip install .

# command to run tests
script: nosetests